# Generated by Django 4.2.3 on 2023-07-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0004_alter_anime_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='img',
        ),
    ]
