# Generated by Django 4.2.3 on 2023-07-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0008_remove_anime_stream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
