# Generated by Django 4.2.3 on 2023-07-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='download_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
