# Generated by Django 4.2.3 on 2023-07-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0012_downloadlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='download_url',
        ),
    ]
