# Generated by Django 4.2.3 on 2023-07-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0013_remove_anime_download_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadLink',
        ),
    ]
